#!/usr/bin/env bash
# tracking system_local after commit because system_local is required to be tracked by nix
echo "adding ./system_local back..."
if git ls-files --error-unmatch ./system_local >> /dev/null; then
	git add ./system_local -r 
fi
