#!/usr/bin/env bash
# avoid committing system_local to git because system_local is required to be tracked by nix
echo "temporarly untracking ./system_local"
if git ls-files --error-unmatch ./system_local >> /dev/null; then
	git rm ./system_local -rf --cached
fi
