#!/usr/bin/env zsh
# zert is a diy plugin manager for zsh

# if --help flag is passed or no command is passed, print help message
if (( $# == 0 )) || [[ "$@[$#]" == "--help" ]]; then
	zert-help $@
elif [[ "$1" == "load" ]]; then
	[[ -z "$2" ]] && echo "plugin url is required" && return
	zert-load $@
elif [[ "$1" == "utilize" ]]; then
	[[ -z "$2" ]] && echo "framework name is required" && return
	zert-utilize $@
elif [[ "$1" == "init" ]]; then
	autoload -Uz $ZDOTDIR/zert/zert-init
	zert-init $@ # because zert function aren't loaded yet
elif [[ "$1" == "apply" ]]; then
	zert-apply $@
elif [[ "$1" == "rm-cache" ]]; then
	zert-rm-cache $@
else
	echo "unkown command"
fi
