#!/usr/bin/env zsh
# this function is used to update zert plugins and frameworks
(){
  setopt local_options no_notify no_monitor no_aliases
  local pids=()
  echo "UPDATING PLUGINS AND FRAMEWORKS...."
  function __update(){
  	git -C "$1" pull -q --recurse-submodules &> /dev/null
  	find -type f -name $1 | grep zwc | xargs rm &> /dev/null
  	zert-compile "$1" &> /dev/null
  }
  for plugin in $(ls -d $ZERTDIR/plugins/*); do
  	__update $plugin &
	pids+=($!)
  done
  for framework in $(ls -d $ZERTDIR/frameworks/*); do
  	__update $plugin &
	pids+=($!)
  done
  for pid in ${pids[@]}; do wait $pid; done
} $@
