#!/usr/bin/env perl
sub on_init {
  my $is_bidi_installed = system("perldoc -l Text::Bidi");
  my $tried_before = system("ls /tmp/tried_installing_bidi");
  my ($self, $pid) = @_;
  if ( $is_bidi_installed != 0 &&  $tried_before != 0){
    system("touch /tmp/tried_installing_bidi");
    system("cpanm Text::Bidi");
    system("urxvt");
    $self->destroy();
  }
}
