#!/usr/bin/env bash
# this file will be sourced by display managers, startx and sx
xrdb ${XDG_CONFIG_HOME:-~/.config}/x11/xresources
systemctl --user import-environment PATH

# all other user services at ~/.config/sytemd/user rely on xsession.target
# so you only need to start xsession.target and all user services will start
# after it
systemctl --no-block --user start xsession.target
